### ISSUE TITLE
How to make and merge to become SDK and mount component?

### ISSUE THREAD

**Issue by chhumsina** [Tyler-Churchill/Embeddable-Widget-Preact-Typescript#137]
Hi there,
it's really nice for your widget.
Anyways, I found the way to create SDK
https://dev.to/mendoza/how-to-build-a-simple-sdk-on-typescript-21gg

But how to merge it with your widget and calling like this.
Example:
js:

 ```
  import Checkout from 'sdk_from_merge_your_widget'
  const checkout = new Checkout(configuration);
  const card = checkout.create('card').mount('#component-container');
```

html:

`<div id="component-container"/></div>`

Thank and appreciate.

**Comment by Tyler-Churchill** [comment]
Hello there, thanks for the interest!

When you run `yarn build` in the project root directory, a "dist" folder is created and contains all of the transpiled code 
"MyWidget-1.0.0.js" and "index.css". These two files need to be embedded and available on the consumer website/DOM for you to be able to instantiate the widget. 
See "/public/index.html" for an example of how this library is currently built to be consumed by users

If you are wanting to use the widget as an es6 module in other projects as you have described, 
you will have to either edit webpack.config.js to export the package as a standard es6 module or use another tool such as 
https://parceljs.org/getting-started/library/  https://parceljs.org/languages/typescript/ to export the code correctly. You will then need to follow other guides on how to properly publish your widget to NPM or the hosted package manager of your choosing. 

You may also get away with importing the widget as `import * as MyWidget from "../path/to/widget/MyWidget-1.0.0" depending on your project setup

The current webpack.config.js is set up is configured in a very specific way to work with the original use of this project. This widget had to be exported as a single vanilla js file and CSS file that could be put onto a CDN so users of the widget could mount and render it in a very traditional way (google tag manager tags, vanilla js and HTML embeds). The exported widget is then available on the webpage under the global "window" object. The original use of the exported widget was not meant to be consumed by other modern apps. This is also why preact was chosen over react as the exported "MyWidget-1.0.0.js" file actually contains the full preact library as well which is why I went with a smaller library size. (example widget is 43KB or 16KB gzipped). 

Unfortunately, I have so many other things on the go I do not see myself reworking this module with export options but hopefully, that is enough information to get you started customizing it to your use case. Any recommendations I could have would be very dependent on your use case and on what websites (angular, vue, react and so on) you are wanting to render your widget on. 

The README.md  "Use Cases" section outlines what use cases the project supports.

* Your widget needs to be easily added to websites with a <script> tag
* Configurable at runtime (publishable keys and other config)
* You find that an iframe is not flexible and feature rich enough for your needs

Cheers! 

Tyler
